// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo25m-OrwFqvh1eh70yqmE2kHW3kleSiA',
    appId: '1:1065983738199:web:e810cc35cb8951effe3e12',
    messagingSenderId: '1065983738199',
    projectId: 'mislab3-d7cdb',
    authDomain: 'mislab3-d7cdb.firebaseapp.com',
    storageBucket: 'mislab3-d7cdb.firebasestorage.app',
    measurementId: 'G-XRK92TDQFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlXJyyeQtnpB4YtSI0luorKmeMginaKI',
    appId: '1:68315441713:android:6f9d0759b6cb36784c0310',
    messagingSenderId: '68315441713',
    projectId: 'misproject-7745b',
    storageBucket: 'misproject-7745b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchAFaYHAwPlLl3gX17w6cCv69rnsi-ZQ',
    appId: '1:1065983738199:ios:0dbb176a7a46c22afe3e12',
    messagingSenderId: '1065983738199',
    projectId: 'mislab3-d7cdb',
    storageBucket: 'mislab3-d7cdb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchAFaYHAwPlLl3gX17w6cCv69rnsi-ZQ',
    appId: '1:1065983738199:ios:0dbb176a7a46c22afe3e12',
    messagingSenderId: '1065983738199',
    projectId: 'mislab3-d7cdb',
    storageBucket: 'mislab3-d7cdb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo25m-OrwFqvh1eh70yqmE2kHW3kleSiA',
    appId: '1:1065983738199:web:cc5c959732e928d2fe3e12',
    messagingSenderId: '1065983738199',
    projectId: 'mislab3-d7cdb',
    authDomain: 'mislab3-d7cdb.firebaseapp.com',
    storageBucket: 'mislab3-d7cdb.firebasestorage.app',
    measurementId: 'G-YY7STTWXVZ',
  );
}
